import ast
from pathlib import Path

try:
    import tomllib
except ImportError:  # Python 3.10
    import tomli as tomllib

from core.exceptions import HelloAgentsException
from runtime.prompt_builder import ContextBuilder


PROJECT_ROOT = Path(__file__).resolve().parent.parent


class _Registry:
    def get_disabled_tools(self):
        return []


def test_code_law_matches_the_current_repository_and_runtime_entrypoint():
    code_law = (PROJECT_ROOT / "code_law.md").read_text(encoding="utf-8")

    assert "runtime/" in code_law
    assert "extensions/" in code_law
    assert "python main.py" in code_law
    assert "agents/" not in code_law
    assert "scripts/chat_test_agent.py" not in code_law
    assert "core/context_engine/" not in code_law


def test_prompt_builder_injects_only_current_project_rules():
    builder = ContextBuilder(
        tool_registry=_Registry(),
        project_root=str(PROJECT_ROOT),
        system_prompt_override="base",
    )

    project_rules = "\n".join(
        message["content"]
        for message in builder.get_prompt_assembly().project_rule_messages
    )

    assert "runtime/" in project_rules
    assert "python main.py" in project_rules
    assert "scripts/chat_test_agent.py" not in project_rules


def test_code_agent_has_no_unused_base_protocol_layer():
    from runtime.host import CodeAgent

    assert not (PROJECT_ROOT / "core" / "agent.py").exists()
    assert CodeAgent.__bases__ == (object,)
    agent = CodeAgent.__new__(CodeAgent)
    agent.name = "code"
    agent.llm = type("LLM", (), {"provider": "openai"})()
    assert str(agent) == "Agent(name=code, provider=openai)"
    assert repr(agent) == "Agent(name=code, provider=openai)"


def test_stable_tools_have_no_runtime_layer_imports():
    violations = []
    for path in (PROJECT_ROOT / "tools").rglob("*.py"):
        tree = ast.parse(path.read_text(encoding="utf-8"), filename=str(path))
        for node in ast.walk(tree):
            if isinstance(node, ast.Import):
                violations.extend(
                    f"{path.relative_to(PROJECT_ROOT)}: {alias.name}"
                    for alias in node.names
                    if alias.name == "runtime" or alias.name.startswith("runtime.")
                )
            elif isinstance(node, ast.ImportFrom) and node.module and (
                node.module == "runtime" or node.module.startswith("runtime.")
            ):
                violations.append(f"{path.relative_to(PROJECT_ROOT)}: {node.module}")

    assert violations == []


def test_runtime_composition_uses_direct_builders_without_a_one_product_factory():
    import runtime.factory as factory

    assert callable(factory.build_runtime_context)
    assert callable(factory.build_runtime_persistence)
    assert callable(factory.create_subagent_launcher)
    assert not hasattr(factory, "RuntimeComponentFactory")


def test_only_the_exception_type_used_by_runtime_remains():
    import core.exceptions as exceptions

    assert exceptions.__all__ == ["HelloAgentsException"]
    assert issubclass(HelloAgentsException, Exception)
    assert not hasattr(exceptions, "LLMException")
    assert not hasattr(exceptions, "AgentException")
    assert not hasattr(exceptions, "ConfigException")
    assert not hasattr(exceptions, "ToolException")


def test_pyproject_is_authoritative_and_requirements_are_uv_exports():
    with (PROJECT_ROOT / "pyproject.toml").open("rb") as project_file:
        project = tomllib.load(project_file)["project"]
    runtime_requirements = (PROJECT_ROOT / "requirements.txt").read_text(encoding="utf-8")
    dev_requirements = (PROJECT_ROOT / "requirements-dev.txt").read_text(encoding="utf-8")

    assert "pydantic>=2.0.0,<3.0.0" in project["dependencies"]
    assert project["optional-dependencies"]["dev"]
    assert "# This file was autogenerated by uv" in runtime_requirements
    assert "pytest" not in runtime_requirements
    assert "# This file was autogenerated by uv" in dev_requirements
    assert "pytest==" in dev_requirements


def test_pydantic_v2_serialization_is_used():
    from core.config import Config
    from tools.base import ToolParameter

    config = Config(enable_mcp=True)
    parameter = ToolParameter(name="path", type="string", description="project path")

    assert config.to_dict() == config.model_dump()
    assert parameter.model_dump() == {
        "name": "path",
        "type": "string",
        "description": "project path",
        "required": True,
        "default": None,
    }


def test_example_base_url_and_cli_copy_are_normalized():
    env_example = (PROJECT_ROOT / ".env.example").read_text(encoding="utf-8")
    cli_source = (PROJECT_ROOT / "app" / "cli.py").read_text(encoding="utf-8")

    assert "LLM_BASE_URL=https://api.siliconflow.cn/v1\n" in env_example
    assert "Initiailizing" not in cli_source
    assert "Initializing Agent Protocol" in cli_source


def test_stable_product_has_no_agent_teams_boundary_leaks():
    """Agent Teams remains discoverable only through the Git-history archive."""
    stable_roots = ("app", "core", "runtime", "tools", "prompts", "utils", "extensions")
    prohibited_symbols = (
        "experimental.teams",
        "enable_agent_teams",
        "agent_teams",
        "TeamManager",
        "TeamCreate",
        "SendMessage",
        "TeamStatus",
        "TeamDelete",
        "TeamCleanup",
        "TeamApprovals",
        "TeamApprovePlan",
        "TeamFanout",
        "TeamCollect",
        "TeamTask",
        "/team ",
        "/delegate",
    )

    stable_sources = [
        source
        for root in stable_roots
        for source in (PROJECT_ROOT / root).rglob("*.py")
    ]
    leaked_symbols = {
        source.relative_to(PROJECT_ROOT).as_posix(): symbol
        for source in stable_sources
        for symbol in prohibited_symbols
        if symbol in source.read_text(encoding="utf-8")
    }

    assert not leaked_symbols
    assert not list((PROJECT_ROOT / "tools" / "builtin").glob("team_*.py"))
    assert not (PROJECT_ROOT / "tools" / "builtin" / "send_message.py").exists()
    assert not list((PROJECT_ROOT / "prompts" / "tools_prompts").glob("team_*.py"))
    assert not (PROJECT_ROOT / "prompts" / "tools_prompts" / "send_message_prompt.py").exists()
    assert not (PROJECT_ROOT / "experimental" / "teams").exists()

    for user_facing_document in ("README.md", "AGENT.md", "docs/HARNESS.md"):
        contents = (PROJECT_ROOT / user_facing_document).read_text(encoding="utf-8")
        assert "Agent Teams" not in contents
        assert "AgentTeams" not in contents


def test_research_archive_points_to_the_exact_pre_removal_commit():
    archive = (PROJECT_ROOT / "docs" / "research-archive.md").read_text(encoding="utf-8")

    assert "f497b172c9bce8279d9a26eb69273e25db7392cf" in archive
